name: Bug report
description: Create a report to help us make the plugin bug free
labels: 'bug'
body:
- type: markdown
  value: |
    Thanks for taking the time to fill out this bug report! Please answer a few questions to make us understand the bug.
    Please make sure that your using the newest version of this plugin and QGIS Version 3.16 or later.
- type: textarea
  id: bug-desc
  attributes:
    label: Describe the bug
    description: Describe how the bug looks like. Also paste error messages and exceptions to give us technical information.
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: How do you trigger this bug? Please walk us through it step by step.
    value: |
      1.
      2.
      3.
      ...
- type: textarea
  id: expection
  attributes:
    label: Expected behavior
    description: Describe what you expected to happen
- type: markdown
  value: '### System information'
- type: input
  id: os
  attributes:
    label: OS
    description: Please submit us your OS with version number
    placeholder: "Windows 10, Ubuntu 18.04, ..."
  validations:
    required: true
- type: input
  id: qgis-version
  attributes:
    label: QGIS Version
    description: "Please enter your QGIS Version. Note: Only QGIS 3.16 and later are supported by this plugin."
    placeholder: "3.20.0, ..."
  validations:
    required: true
