name: Bug report
description: Report a bug to help us make the program bug-free.
labels: bug
assignees: bennetrr
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this bug report! Please answer a few questions to help us better understand the bug.
      Please make sure that you are using the latest version of the program and also have all dependencies installed if applicable (e.g. QGIS 3.16).
      Also, check [here](https://github.com/bennetrr/QGIS-Layer-Geocode/issues?q=is%3Aissue+label%3Abug) to see if someone else has not already reported this or a related bug.
- type: textarea
  id: bug-desc
  attributes:
    label: Bug description
    description: Describe what the error looks like. Also include error messages and exceptions to give us technical information. Also paste screenshots here.
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: |
      How did you trigger the error? Please tell us step by step what you did when / before the error was triggered.
      This will allow us to trigger the error ourselves and take it to pieces with our tools.
    value: |
      1.
      2.
      3.
      ...
- type: markdown
  attributes:
    value: '# System information'
- type: input
  id: os
  attributes:
    label: Operating system
    description: Please tell us your operating system. Please also give us the version number.
    placeholder: Windows 10, Ubuntu 21.04, ...
  validations:
    required: true
- type: input
  id: qgis-version
  attributes:
    label: QGIS version
    description: Please specify your QGIS version.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      That's it! Your bug report will be processed by us after you send it.
